In [70]:
#autograd is a package use for the gradient calculation 
#graadients are the essential key componants for out model optimization 
#the pytorch provides the autograd package that perform all the nesseay calculation for us 
#torch.autograd does the automatic differentitation by collecting all the gradients 


In [71]:
import torch
#creating the tensor with the shape off 3 and with argumentif requires_grad=True
x=torch.rand(3,requires_grad=True)
x

tensor([0.0795, 0.1180, 0.3702], requires_grad=True)

In [72]:
#if we are performing the y=x+2 means it ceate graph 
#the graph look like this 
"""
 forward propogation
->->->->->->->->->->->-> we calculate y 
x
 \
  \
   \  ________
    \ |      |
     \|      |
     /|   +  |------------->y
    / |      |
   /  ---------
  /
 /
2
<-<-<-<-<-<-<-<-<-<-<-<- 
back propogation using the dy/dx

first perform forward propogatoon later perform the back propogatiion based the loss(otginal_value-y)
"""
y=x+2
y    #grad_fn=<AddBackward0> tell operation used to obtain the tensor

tensor([2.0795, 2.1180, 2.3702], grad_fn=<AddBackward0>)

In [73]:
#applying thee multiple operation on the tensor 
z=y*y+2
print(z)

tensor([6.3244, 6.4860, 7.6177], grad_fn=<AddBackward0>)


In [74]:
z=z.mean()
z

tensor(6.8094, grad_fn=<MeanBackward0>)

In [75]:
#to calculate the gradients  we need to class the backweord() function 
z.backward()  #perform the dz/dx
#gradients  are stored in the x     #backward onlu performed on the single or scalar  value or 1D tensor
#else if z is 2D tensor means this  error will return ""grad can be implicitly created only for scalar outputs""

x.grad   #tensor([6.9430 6.8489, 7.2088])

tensor([1.3863, 1.4120, 1.5801])

In [76]:
#stopping the pytorch from creating the gradients (preventing the gradient history)
"""
there are three methods 
1:variable.requires_grad=False  
2.new variable=variable.detach() this will create a new tensor that doesnot require the gradient 
3.waping the code on the with torch.torch.no_grad(): the code inside this will not create gradient  
"""
x=torch.empty(4,5,requires_grad=True)
#methoad1
print("before applying the method 1:x:",x)
x.requires_grad=False
print("after applying the modehod 1:x:",x) #requires_grad=True dispear means if we pass this as a parameter means the optimiation will not be performed .



#method2 
x=torch.empty(4,5,requires_grad=True)
print("before applying the method 2:x:",x)
x.detach_()  #applying the inplace operation
print("after applying the modehod 2:x:",x) 




#method3 
x=torch.empty(4,5,requires_grad=True)
print("before applying the method 3:x:",x)
with torch.no_grad():
    y=x*2
print("after applying the modehod 3:x:",x)
print("after applying the modehod 3:y:",y) #here y doesnot have the gradient because it is created withing the wap o the the with torch.no_grad()

before applying the method 1:x: tensor([[2.1943e+17, 7.4689e-43, 2.1942e+17, 7.4689e-43, 2.2085e+17],
        [7.4689e-43, 2.2085e+17, 7.4689e-43, 2.2086e+17, 7.4689e-43],
        [2.2086e+17, 7.4689e-43, 2.2090e+17, 7.4689e-43, 2.2090e+17],
        [7.4689e-43, 2.2086e+17, 7.4689e-43, 2.2086e+17, 7.4689e-43]],
       requires_grad=True)
after applying the modehod 1:x: tensor([[2.1943e+17, 7.4689e-43, 2.1942e+17, 7.4689e-43, 2.2085e+17],
        [7.4689e-43, 2.2085e+17, 7.4689e-43, 2.2086e+17, 7.4689e-43],
        [2.2086e+17, 7.4689e-43, 2.2090e+17, 7.4689e-43, 2.2090e+17],
        [7.4689e-43, 2.2086e+17, 7.4689e-43, 2.2086e+17, 7.4689e-43]])
before applying the method 2:x: tensor([[9.0919e-39, 9.2755e-39, 2.9389e-39, 1.0286e-38, 1.0469e-38],
        [1.0653e-38, 1.0194e-38, 2.9389e-39, 1.0194e-38, 9.9184e-39],
        [2.9389e-39, 1.0194e-38, 2.9389e-39, 9.2755e-39, 9.0918e-39],
        [1.0010e-38, 9.9184e-39, 1.0653e-38, 9.1837e-39, 9.6428e-39]],
       requires_grad=True)
after a

In [77]:
#creating the some training excerize 
weights = torch.ones(10,requires_grad=True)
for i in range(5):
    model_output= (weights*3).sum()
    model_output.backward()
    print(f"model output gradients at iteration:{i},graadients:{weights.grad}")

model output gradients at iteration:0,graadients:tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
model output gradients at iteration:1,graadients:tensor([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])
model output gradients at iteration:2,graadients:tensor([9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])
model output gradients at iteration:3,graadients:tensor([12., 12., 12., 12., 12., 12., 12., 12., 12., 12.])
model output gradients at iteration:4,graadients:tensor([15., 15., 15., 15., 15., 15., 15., 15., 15., 15.])


In [68]:
#main problem in the above cell is got every epoch the gradients should be zero because the previous gradients should not effect the frature ateration 
weights = torch.ones(10,requires_grad=True)
for i in range(5):
    model_output= (weights*3).sum()
    model_output.backward()
    print(f"model output gradients at iteration:{i},graadients:{weights.grad}")
    #now converting the gradoents into 0 
    #weights.grad=torch.zeros(weights.grad.size()[0])
    #or
    weights.grad.zero_()
    #both do the same operation

model output gradients at iteration:0,graadients:tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
model output gradients at iteration:1,graadients:tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
model output gradients at iteration:2,graadients:tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
model output gradients at iteration:3,graadients:tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
model output gradients at iteration:4,graadients:tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])


In [87]:
#importing the torch optimizer from the torch.optim package 
#impoting the SGD  optimizer 
from torch.optim import SGD
weights = torch.ones(10,requires_grad=True)
print("weights before optimizer:",weights)
#in optimizer we need to pass the weights which are iteratable but tensor is not iteratable so we will pass tensor as list
SGD_optimizer= SGD([weights],lr=0.01) #this will take the weights as the parameter and the teh lrarning rate 
#step function is resplnsible for updating the weights and biases of the neural network based on the gradients.
SGD_optimizer.step()
print("weights after optimizer step:",weights)

weights before optimizer: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)
weights after optimizer step: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)


In [97]:
#running the uotimizer for 3 iterations 
#creating the weiights trnsor with the size of 5 and enebling the gradients 
weights = torch.ones(10,requires_grad=True)
SGD_optimizer=torch.optim.SGD([weights],lr=0.01)
for i in range(5):
    print(f"weights before iteration{i+1}:{weights}")
    SGD_optimizer.step()
    print(f"weights after iteration{i+1}:{weights.grad}")
    print("====================================")
SGD_optimizer.zero_grad()  #set gradient of all the parameters to zero 

weights before iteration1:tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)
weights after iteration1:None
weights before iteration2:tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)
weights after iteration2:None
weights before iteration3:tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)
weights after iteration3:None
weights before iteration4:tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)
weights after iteration4:None
weights before iteration5:tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)
weights after iteration5:None
