In [2]:
import torch

In [24]:
#backpropogation perform the backward pass to adjust the modal parameters to minimize the mean sqare error
"""
it is a process involved in the training of the neural network .
it involves in the taking the output of the feed forward network  and calculate the loss 
it use the loadd  and perform the backword pass to adjust the model parameters to minimize the loss or mean aware error 

in the backpropogation we will calculate the deratives 
"""

#operations are  performed in the backpropogation 
1.

1.0

In [34]:
#creatuing the thesor 
x=torch.tensor(4.0,requires_grad=True)

In [35]:
y=x**2
#deratie(x**n)=n*x**(n-1)
#x**2---->derative(x**2)=2x
y

tensor(16., grad_fn=<PowBackward0>)

In [36]:
#performanning the backword function
y.backward()
y

tensor(16., grad_fn=<PowBackward0>)

In [38]:
#getting the gradient of the x
x.grad     #2x

tensor(8.)

In [42]:
#creating the complex tensor 
x=torch.tensor([[1.,2.,3.,4.,5.,6.,7.,8.,9.],[9.,8.,7.,6.,5.,4.,3.,2.,1.],[1.,2.,3.,4.,5.,6.,7.,8.,9.],[9.,8.,7.,6.,5.,4.,3.,2.,1.]],requires_grad=True)
x

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 8., 7., 6., 5., 4., 3., 2., 1.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 8., 7., 6., 5., 4., 3., 2., 1.]], requires_grad=True)

In [55]:
y=x**3+x**2    #derative(x**3+x**2)=3x**2+2x
y.sum().backward()
y

tensor([[  2.,  12.,  36.,  80., 150., 252., 392., 576., 810.],
        [810., 576., 392., 252., 150.,  80.,  36.,  12.,   2.],
        [  2.,  12.,  36.,  80., 150., 252., 392., 576., 810.],
        [810., 576., 392., 252., 150.,  80.,  36.,  12.,   2.]],
       grad_fn=<AddBackward0>)

In [48]:
x.grad

tensor([[  5.,  16.,  33.,  56.,  85., 120., 161., 208., 261.],
        [261., 208., 161., 120.,  85.,  56.,  33.,  16.,   5.],
        [  5.,  16.,  33.,  56.,  85., 120., 161., 208., 261.],
        [261., 208., 161., 120.,  85.,  56.,  33.,  16.,   5.]])

In [63]:
3*x**2+2*x

tensor([[  5.,  16.,  33.,  56.,  85., 120., 161., 208., 261.],
        [261., 208., 161., 120.,  85.,  56.,  33.,  16.,   5.],
        [  5.,  16.,  33.,  56.,  85., 120., 161., 208., 261.],
        [261., 208., 161., 120.,  85.,  56.,  33.,  16.,   5.]],
       grad_fn=<AddBackward0>)